#let data = json("data.json")

#set page(
  margin: (x: 1in, y: 1in),
  footer: [
    #set text(size: 8pt, fill: gray)
    #align(center)[Generated by Scribe.ai]
  ]
)

#set text(
  font: "Inter",
  size: 10pt,
  fill: rgb("#000000")
)

// Header
#align(right)[
  #text(size: 14pt, weight: "bold")[#data.profile.name] \
  #data.profile.email \
  #data.profile.phone \
  #data.profile.location
]

#v(2em)

// Date
#datetime.today().display("[month repr:long] [day], [year]")

#v(1em)

// Salutation
Dear Hiring Manager,

#v(1em)

// Body
#eval(data.content, mode: "markup")

#v(2em)

Sincerely, \
#v(1em)
#data.profile.name
